source 'https://rubygems.org'
gem 'unicorn'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sass'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'activesupport', '~>4.1'
gem 'builder'
gem 'oauth'
gem 'unicorn-worker-killer'
